python2 pm_patterns_export.py -d ../data/10fold-buildyara/0/ -o ../config/train-0.yara
python2 pm_patterns_export.py -d ../data/10fold-buildyara/1/ -o ../config/train-1.yara
python2 pm_patterns_export.py -d ../data/10fold-buildyara/2/ -o ../config/train-2.yara
python2 pm_patterns_export.py -d ../data/10fold-buildyara/3/ -o ../config/train-3.yara
python2 pm_patterns_export.py -d ../data/10fold-buildyara/4/ -o ../config/train-4.yara
python2 pm_patterns_export.py -d ../data/10fold-buildyara/5/ -o ../config/train-5.yara
python2 pm_patterns_export.py -d ../data/10fold-buildyara/6/ -o ../config/train-6.yara
python2 pm_patterns_export.py -d ../data/10fold-buildyara/7/ -o ../config/train-7.yara
python2 pm_patterns_export.py -d ../data/10fold-buildyara/8/ -o ../config/train-8.yara
python2 pm_patterns_export.py -d ../data/10fold-buildyara/9/ -o ../config/train-9.yara
